apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      tier: web
  template:
    metadata:
      labels:
        name: web
        tier: web
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: techworldwithsiva/web:k8
        resources:
          requests:
            cpu: "100m"
            memory: "156Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80